In [1]:
import pandas as pd

In [2]:
train_sample = pd.read_csv("../data/train.csv", nrows=10000)

In [3]:
train_sample.head()

   id        date  store_nbr  item_nbr  unit_sales  onpromotion
0   0  2013-01-01         25    103665         7.0          NaN
1   1  2013-01-01         25    105574         1.0          NaN
2   2  2013-01-01         25    105575         2.0          NaN
3   3  2013-01-01         25    108079         1.0          NaN
4   4  2013-01-01         25    108701         1.0          NaN

In [4]:
train_sample.shape

(10000, 6)

In [5]:
train_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           10000 non-null  int64
 1   date         10000 non-null  object
 2   store_nbr    10000 non-null  int64
 3   item_nbr     10000 non-null  int64
 4   unit_sales   10000 non-null  float64
 5   onpromotion  0 non-null      float64
dtypes: float64(2), int64(3), object(1)
memory usage: 468.9+ KB

In [6]:
train_sample.isnull().sum()

id                 0
date               0
store_nbr          0
item_nbr           0
unit_sales         0
onpromotion    10000
dtype: int64

In [7]:
train_sample["date"].min(), train_sample["date"].max()

('2013-01-01', '2013-01-02')

In [8]:
train_sample["store_nbr"].nunique(), train_sample["item_nbr"].nunique()

(10, 1469)

In [9]:
train_sample["date"] = pd.to_datetime(train_sample["date"])

In [10]:
train_sample["unit_sales"].describe()

count    10000.000000
mean        11.498949
std         17.222499
min          0.252000
25%          3.000000
50%          6.000000
75%         13.000000
max        483.000000
Name: unit_sales, dtype: float64

In [11]:
train_sample["unit_sales"].sum(), train_sample["unit_sales"].mean()

(np.float64(114989.486), np.float64(11.4989486))

In [12]:
target_store = 25
target_item = 103665

chunks = []

for chunk in pd.read_csv(
    "../data/train.csv",
    chunksize=500000
):
    filtered = chunk[
        (chunk["store_nbr"] == target_store) &
        (chunk["item_nbr"] == target_item)
    ]
    
    if not filtered.empty:
        chunks.append(filtered)

product_sales = pd.concat(chunks, ignore_index=True)

product_sales["date"] = pd.to_datetime(product_sales["date"])

product_sales.head()

C:\Users\hp\AppData\Local\Temp\ipykernel_27520\1006769183.py:6: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(

       id       date  store_nbr  item_nbr  unit_sales onpromotion
0       0 2013-01-01         25    103665         7.0         NaN
1   19811 2013-01-02         25    103665         5.0         NaN
2  100696 2013-01-04         25    103665         5.0         NaN
3  141831 2013-01-05         25    103665         5.0         NaN
4  183815 2013-01-06         25    103665         7.0         NaN

In [13]:
product_sales.shape

(1142, 6)

In [14]:
product_sales["date"].min(), product_sales["date"].max()

(Timestamp('2013-01-01 00:00:00'), Timestamp('2017-08-15 00:00:00'))

In [15]:
product_sales.tail()

             id       date  store_nbr  item_nbr  unit_sales onpromotion
1137  125019493 2017-08-11         25    103665         6.0       False
1138  125125144 2017-08-12         25    103665        10.0       False
1139  125230204 2017-08-13         25    103665         2.0       False
1140  125336140 2017-08-14         25    103665         2.0       False
1141  125438641 2017-08-15         25    103665         1.0       False